// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriTic.App.Persistencia;

namespace NutriTic.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211011163413_Entidades")]
    partial class Entidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NutriTic.App.Dominio.CargoEmpleado", b =>
                {
                    b.Property<int>("IdCargoEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCargoEmpleado");

                    b.ToTable("CargoEmpleado");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.Empleado", b =>
                {
                    b.Property<string>("IdEmpleado")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<int>("IdCargoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdCargoEmpleado");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.Medida", b =>
                {
                    b.Property<int>("IdMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("IdPaciente")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("IdMedida");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Medida");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.Paciente", b =>
                {
                    b.Property<string>("IdPaciente")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Estatura")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Latitud")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Longitud")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdPaciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.PacienteEmpleado", b =>
                {
                    b.Property<int>("IdPacienteEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("IdEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("IdPaciente")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdPacienteEmpleado");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdPaciente");

                    b.ToTable("PacienteEmpleado");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.Valoracion", b =>
                {
                    b.Property<int>("IdValoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("IdEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("IdMedida")
                        .HasColumnType("int");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdValoracion");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdMedida");

                    b.ToTable("Valoracion");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.Empleado", b =>
                {
                    b.HasOne("NutriTic.App.Dominio.CargoEmpleado", "CargoEmpleado")
                        .WithMany()
                        .HasForeignKey("IdCargoEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoEmpleado");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.Medida", b =>
                {
                    b.HasOne("NutriTic.App.Dominio.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.PacienteEmpleado", b =>
                {
                    b.HasOne("NutriTic.App.Dominio.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTic.App.Dominio.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriTic.App.Dominio.Valoracion", b =>
                {
                    b.HasOne("NutriTic.App.Dominio.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTic.App.Dominio.Medida", "Medida")
                        .WithMany()
                        .HasForeignKey("IdMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Medida");
                });
#pragma warning restore 612, 618
        }
    }
}
